services:

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: api_postgres
    container_name: api_postgres

  api:
    build: .
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    hostname: api
    container_name: api
    command: uvicorn app:app --reload --host 0.0.0.0

volumes:
  postgres:
