services:

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: money_postgres
    container_name: money_postgres

  money:
    build: .
    volumes:
      - .:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    hostname: money
    container_name: money
    command: uvicorn app:app --reload --host 0.0.0.0

volumes:
  postgres:
